baseURL = 'http://example.org/'
languageCode = 'zh-us'
title = '清 余'
theme = 'hugo-theme-stack'

DefaultContentLanguage = "zh-cn"


[params]
mainSections = [ "post" ]
featuredImageField = "image"
rssFullContent = true

[params.footer]
since = 2023
customText = "> 语雀：[QING-YU](https://www.yuque.com/qingyu-mj828)"

[params.dateFormat]
published = "Jan 02, 2006"
lastUpdated = "Jan 02, 2006 15:04 MST"

[params.sidebar]
compact = false
emoji = "⚒"
subtitle = "燕山大学 软件工程专业  21级就读"

[params.sidebar.avatar]
enabled = true
local = true
src = "imgs/header.png"

[params.article]
math = false
toc = true
readingTime = true

[params.article.license]
enabled = false
default = "Licensed under CC BY-NC-SA 4.0"

[params.comments]
enabled = true
provider = "utterances"

[params.comments.utterances]
repo = "QING-YU123/comments"
issueTerm = "pathname"

[params.widgets]
[[params.widgets.homepage]]
type = "search"

[[params.widgets.homepage]]
type = "archives"

[params.widgets.homepage.params]
limit = 5

[[params.widgets.homepage]]
type = "categories"

[params.widgets.homepage.params]
limit = 10

[[params.widgets.homepage]]
type = "tag-cloud"

[params.widgets.homepage.params]
limit = 10

[[params.widgets.page]]
type = "toc"

[params.opengraph]
[params.opengraph.twitter]
card = "summary_large_image"

[params.defaultImage]
[params.defaultImage.opengraph]
enabled = false
local = false

[params.colorScheme]
toggle = true
default = "auto"

[params.imageProcessing]
[params.imageProcessing.cover]
enabled = true

[params.imageProcessing.content]
enabled = true